### ISSUE TITLE
1.3.2 Placing blocks plays a sound twice

### ISSUE THREAD

**Issue by DeadbushCarrot** [ViaVersion/ViaLegacy#33]
### General Information

A lot of mods (105)  
I really don't want list all of that

### Bug Description

Any time you place down a block it will play the the normal place sound then a walking one or something else

### Steps to Reproduce

1 join a 1.3.2 server 
2 place down a block

### Expected Behavior

I expect it just to play the placing sound

**Comment by FlorianMichael** [comment]
I'm going to close this issue as it also appears when using 1.8 and 1.13 in ViaFabricPlus, so it's not a ViaLegacy issue

https://github.com/ViaVersion/ViaFabricPlus/issues/333

**Comment by splice11** [comment]
I am not a programmer, but I think it could be related to hypixel's ping hiding. Hypixel shows everyone as having 1ms ping, (they started doing this couple years ago).
Other servers that don't hide ping don't have this.

**Comment by FlorianMichael** [comment]
ViaVersion/ViaLegacy don't use the ping value for protocol translation

**Comment by FlorianMichael** [comment]
Issue got fixed with https://github.com/ViaVersion/ViaVersion/pull/3886
