### ISSUE TITLE
[Question] hello, do you know how to send backwards packets for 1.6.4-1.4.6 using vialegacy?

### ISSUE THREAD

**Issue by Outfit8TSB** [ViaVersion/ViaLegacy#87]
i am using ViaLegacy on [My own Bukkit Project Called ViaVersionProtocolSupport](https://github.com/GAME-CLI-SRV-DEV/ViaVersionProtocolSupport), that makes 1.4.6-1.6.4 able to go to 1.7.2-1.21.1 Server.
but i dont know how to make old clients join new server version and send their packets. if you know how, please answer. 
i know that the effort required to allow old clients to join 1.19 servers is enormous, And not many would use that, but it's courtesy for ProtocolSupport Users who want to use 1.21, especially Who Wants to Use ProtocolSupportBungee on Velocity like minewind.

**Comment by RaphiMC** [comment]
ViaLegacy does not contain any code to allow for backwards support. You need to figure that out on your own

**Comment by Outfit8TSB** [comment]
ok.

**Comment by Outfit8TSB** [comment]
UPDATE: I Found it, using ViaBackwards Template must be solution

**Comment by RaphiMC** [comment]
@Outfit8TSB Please stop replying to closed issues
